version: '3'

services:
  database:
    build:
      context: .docker/mysql
    container_name: blog-mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=blog
    volumes:
      - database_data:/var/lib/mysql:rw
    ports:
      - "3306:3306"

  apache:
    container_name: blog-apache
    image: php8.2-apache
    build:
      context: .docker/apache
    working_dir: /var/www
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www

volumes:
  database_data:
